// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Ludwig.Data.Models;

public partial class BookingSystemContext : DbContext
{
    public BookingSystemContext()
    {
    }

    public BookingSystemContext(DbContextOptions<BookingSystemContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Prenotazione> Prenotazione { get; set; }

    public virtual DbSet<Risorsa> Risorsa { get; set; }

    public virtual DbSet<TipoRisorsa> TipoRisorsa { get; set; }

    public virtual DbSet<Utente> Utente { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Prenotazione>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.A).HasColumnType("datetime");
            entity.Property(e => e.Da).HasColumnType("datetime");
            entity.Property(e => e.Stato).HasMaxLength(50);

            entity.HasOne(d => d.Risorsa).WithMany(p => p.Prenotazione)
                .HasForeignKey(d => d.RisorsaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_PrenotazioniRisorsa");

            entity.HasOne(d => d.Utente).WithMany(p => p.Prenotazione)
                .HasForeignKey(d => d.UtenteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_PrenotazioniUtente");
        });

        modelBuilder.Entity<Risorsa>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Ubicazione).HasMaxLength(50);

            entity.HasOne(d => d.IdTipoNavigation).WithMany(p => p.Risorsa)
                .HasForeignKey(d => d.IdTipo)
                .HasConstraintName("fk_TipoRisorsa");
        });

        modelBuilder.Entity<TipoRisorsa>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Nome).HasMaxLength(50);
        });

        modelBuilder.Entity<Utente>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Dipartimento).HasMaxLength(50);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Ruolo).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}