// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ludwig.Data.Models;

public partial class Prenotazione
{
    public int Id { get; set; }

    public int RisorsaId { get; set; }

    public int UtenteId { get; set; }
    public int DottoreId { get; set; }

    public DateTime Da { get; set; }

    public DateTime A { get; set; }

    public string Stato { get; set; }

    public virtual Risorsa Risorsa { get; set; }

    public virtual Utente Utente { get; set; }
}