// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ludwig.Data.Models;

public partial class Risorsa
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public int? IdTipo { get; set; }

    public int? Capacità { get; set; }

    public string Ubicazione { get; set; }

    public virtual TipoRisorsa IdTipoNavigation { get; set; }

    public virtual ICollection<Prenotazione> Prenotazione { get; set; } = new List<Prenotazione>();
}