// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ludwig.Data.Models;

public partial class TipoRisorsa
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public virtual ICollection<Risorsa> Risorsa { get; set; } = new List<Risorsa>();
}