// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Ludwig.Data.Models;

public partial class Utente
{
    public int Id { get; set; }

    public string Nome { get; set; }

    public string Email { get; set; }

    public string Dipartimento { get; set; }

    public string Ruolo { get; set; }

    public virtual ICollection<Prenotazione> Prenotazione { get; set; } = new List<Prenotazione>();
}